version: '3'

services:
  redis-node1:
    image: redis:latest
    ports:
      - "7000:7000"
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_TIMEOUT=5000
    networks:
      - rediscluster

  redis-node2:
    image: redis:latest
    ports:
      - "7001:7001"
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_TIMEOUT=5000
    networks:
      - rediscluster

  redis-node3:
    image: redis:latest
    ports:
      - "7002:7002"
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_TIMEOUT=5000
    networks:
      - rediscluster

networks:
  rediscluster: