version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5985:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=0000
    volumes:
        - ./dbdata:/opt/couchdb/data